image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
  - docker login --username=$QUAY_HUB_USER --password=$QUAY_HUB_PASS quay.io
  - docker login --username=$GITHUB_HUB_USER --password=$GITHUB_HUB_PASS docker.pkg.github.com

build:
  stage: build
  script:
    # build
    - docker build -f Dockerfile -t aasaam/web-server .
    # push
    - docker push aasaam/web-server
    # push quay.io
    - |
      docker image tag aasaam/web-server quay.io/aasaam/web-server
      docker push quay.io/aasaam/web-server
      docker image tag aasaam/web-server docker.pkg.github.com/aasaam/web-server/web-server
      docker push docker.pkg.github.com/aasaam/web-server/web-server
    # remove image
    - docker rmi aasaam/web-server
