version: '3'

services:
  aasaam-web-server:
    container_name: aasaam-web-server
    image: aasaam/web-server
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./tmp/log:/log
      - ./tmp/cache:/cache # use tmpfs or high speed storage like SSD or NVMe
      - ./addon:/usr/local/openresty/nginx/addon:ro
    restart: unless-stopped
