# Copyright (c) 2021 aasaam software development group
version: '3'

services:
  aasaam-web-server:
    container_name: aasaam-web-server
    image: aasaam/web-server
    network_mode: host
    environment:
      ASM_CACHE_SIZE_MB: ${ASM_CACHE_SIZE_MB:-'1024'}
      ASM_CLIENT_BODY_TIMEOUT: ${ASM_CLIENT_BODY_TIMEOUT:-'15'}
      ASM_CLIENT_MAX_BODY_SIZE: ${ASM_CLIENT_MAX_BODY_SIZE:-'10M'}
      ASM_HTTPS_PORTS: ${ASM_HTTPS_PORTS:-'443'}
      ASM_HTTP_PORTS: ${ASM_HTTP_PORTS:-'80'}
      ASM_KEEPALIVE_REQUESTS: ${ASM_KEEPALIVE_REQUESTS:-'1024'}
      ASM_KEEPALIVE_TIMEOUT: ${ASM_KEEPALIVE_TIMEOUT:-'10'}
      ASM_LOG_METHOD: ${ASM_LOG_METHOD:-'syslog'}
      ASM_LOG_SYSLOG_SERVER_ADDR: ${ASM_LOG_SYSLOG_SERVER_ADDR:-'127.0.0.1:5140'}
      ASM_NGINX_MAIN_LOG_LEVEL: ${ASM_NGINX_MAIN_LOG_LEVEL:-'warn'}
      ASM_NGINX_WORKER_CONNECTIONS: ${ASM_NGINX_WORKER_CONNECTIONS:-'8192'}
      ASM_NGINX_WORKER_PROCESSES: ${ASM_NGINX_WORKER_PROCESSES:-'auto'}
      ASM_NGINX_WORKER_RLIMIT_NOFILE: ${ASM_NGINX_WORKER_RLIMIT_NOFILE:-'20480'}
      ASM_NODE_ID: ${ASM_NODE_ID:-'0'}
      ASM_OPEN_FILE_CACHE_ERRORS: ${ASM_OPEN_FILE_CACHE_ERRORS:-'on'}
      ASM_OPEN_FILE_CACHE_INACTIVE: ${ASM_OPEN_FILE_CACHE_INACTIVE:-'10m'}
      ASM_OPEN_FILE_CACHE_MAX: ${ASM_OPEN_FILE_CACHE_MAX:-'1024'}
      ASM_OPEN_FILE_CACHE_MIN_USES: ${ASM_OPEN_FILE_CACHE_MIN_USES:-'2'}
      ASM_OPEN_FILE_CACHE_VALID: ${ASM_OPEN_FILE_CACHE_VALID:-'5m'}
      ASM_ORGANIZATION_BRAND_ICON: ${ASM_ORGANIZATION_BRAND_ICON:-'ir_aasaam'}
      ASM_ORGANIZATION_TITLE: ${ASM_ORGANIZATION_TITLE:-'aasaam software development group'}
      ASM_PROTECTION_CONN_LIMIT_PER_IP_ZONE: ${ASM_PROTECTION_CONN_LIMIT_PER_IP_ZONE:-'10m'}
      ASM_PROTECTION_REQ_LIMIT_IP_PER_SECOND: ${ASM_PROTECTION_REQ_LIMIT_IP_PER_SECOND:-'10'}
      ASM_PROTECTION_REQ_LIMIT_PER_IP_ZONE: ${ASM_PROTECTION_REQ_LIMIT_PER_IP_ZONE:-'10m'}
      ASM_PROXY_BUFFERS: ${ASM_PROXY_BUFFERS:-'32'}
      ASM_PROXY_BUFFERS_SIZE: ${ASM_PROXY_BUFFERS_SIZE:-'128k'}
      ASM_PROXY_BUFFER_SIZE: ${ASM_PROXY_BUFFER_SIZE:-'256k'}
      ASM_PROXY_CACHE_KEY: ${ASM_PROXY_CACHE_KEY:-'$scheme$request_method$host$request_uri'}
      ASM_PROXY_CACHE_METHODS: ${ASM_PROXY_CACHE_METHODS:-'GET HEAD'}
      ASM_PROXY_CACHE_PATH_KEYS_INACTIVE: ${ASM_PROXY_CACHE_PATH_KEYS_INACTIVE:-'60m'}
      ASM_PROXY_CACHE_PATH_KEYS_MAX_SIZE_MB: ${ASM_PROXY_CACHE_PATH_KEYS_MAX_SIZE_MB:-'512'}
      ASM_PROXY_CACHE_PATH_KEYS_ZONE: ${ASM_PROXY_CACHE_PATH_KEYS_ZONE:-'32m'}
      ASM_RESOLVER_ADDR: ${ASM_RESOLVER_ADDR:-'127.0.0.1'}
      ASM_RESOLVER_VALID: ${ASM_RESOLVER_VALID:-'10m'}
      ASM_SEND_TIMEOUT: ${ASM_SEND_TIMEOUT:-'10'}
      ASM_SERVER_TRAFFIC_STATUS_ZONE: ${ASM_SERVER_TRAFFIC_STATUS_ZONE:-'16m'}
      ASM_SSL_PROFILE: ${ASM_SSL_PROFILE:-'intermediate'}
      ASM_VARIABLES_HASH_MAX_SIZE: ${ASM_VARIABLES_HASH_MAX_SIZE:-'4096'}
    volumes:
      # - ./tmp/log:/log # for file log method
      - ./addon:/usr/local/openresty/nginx/addon:ro
      - ./tmp/dhparams.pem:/usr/local/openresty/nginx/dhparams.pem:ro
      # - ./tmp/cache:/cache # use tmpfs or high speed storage like SSD, NVMe
    tmpfs:
      - /cache:rw,nodev,nosuid,noexec,noatime,size=${ASM_CACHE_SIZE_MB:-1024}m
    restart: unless-stopped
