#!/usr/bin/env python3

suspicious_list = [
  {
    "category": "ios",
    "extensions": [
      "hqx",
      "ipa",
    ],
  },
  {
    "category": "android",
    "extensions": [
      "aab",
      "apk",
      "apkm",
      "apks",
      "obb",
      "xapk",
    ],
  },
  {
    "category": "windows phone",
    "extensions": [
      "xap",
    ],
  },
  {
    "category": "security",
    "extensions": [
      "arm",
      "ca-bundle",
      "cer",
      "crt",
      "der",
      "key",
      "keystore",
      "jks",
      "pvb",
      "pvc",
      "pvs",
      "pvr",
      "p12",
      "p7b",
      "p7s",
      "pem",
      "pfx",
      "spc",
      "yara",
    ],
  },
  {
    "category": "apache xmlbeans",
    "extensions": [
      "xsb",
    ],
  },
  {
    "category": "apache ",
    "extensions": [
      "htaccess",
      "htpasswd",
    ],
  },
  {
    "category": "configuration",
    "extensions": [
      "conf",
      "ini",
      "json",
      "toml",
      "xml",
      "yml",
      "yaml",
    ],
  },
  {
    "category": "windows",
    "extensions": [
      "app",
      "ade",
      "adp",
      "application",
      "appx",
      "appxbundle",
      "bat",
      "btm",
      "bin",
      "cab",
      "cmd",
      "com",
      "cpl",
      "csh",
      "cnt",
      "dll",
      "drv",
      "exe",
      "gadget",
      "hta",
      "hpj",
      "hlp",
      "lib",
      "isp",
      "ocx",
      "osd",
      "ops",
      "icl",
      "inf",
      "inf1",
      "ins",
      "inx",
      "isu",
      "job",
      "jse",
      "jst",
      "lnk",
      "mad",
      "maf",
      "mag",
      "mam",
      "mat",
      "mda",
      "mas",
      "mau",
      "maq",
      "maw",
      "mav",
      "msc",
      "msh",
      "mar",
      "msh1",
      "msh1xml",
      "msh2",
      "msh2xml",
      "mshxml",
      "msi",
      "msp",
      "mst",
      "paf",
      "pif",
      "ps1",
      "ps1xml",
      "ps2",
      "ps2xml",
      "psc1",
      "psc2",
      "psd1",
      "psm1",
      "pst",
      "prg",
      "prf",
      "plg",
      "pcd",
      "reg",
      "rgs",
      "run",
      "scf",
      "scr",
      "sct",
      "sfx",
      "shb",
      "shs",
      "tmp",
      "u3p",
      "vb",
      "vbe",
      "vbs",
      "vbscript",
      "xnk",
      "xgs",
      "xwb",
      "ws",
      "wsc",
      "wsf",
      "wsh",
    ],
  },
  {
    "category": "linux",
    "extensions": [
      "a",
      "ash",
      "bash",
      "csh",
      "deb",
      "rpm",
      "rsh",
      "ksh",
      "msh",
      "psh",
      "sh",
      "ssh",
      "so",
      "tcsh",
      "zsh",
    ],
  },
  {
    "category": "php",
    "extensions": [
      "ctp",
      "php",
      "php3",
      "php4",
      "php5",
      "php6",
      "php7",
      "php8",
      "phtml",
      "twig",
    ],
  },
  {
    "category": "basic",
    "extensions": [
      "bas",
    ],
  },
  {
    "category": "asp",
    "extensions": [
      "asa",
      "asax",
      "ascx",
      "ashx",
      "asmx",
      "asp",
      "aspx",
      "axd",
      "browser",
      "cd",
      "cdx",
      "compile",
      "config",
      "cs",
      "csproj",
      "disco",
      "dsdgm",
      "dsprototype",
      "grp",
      "idc",
      "jsl",
      "ldb",
      "licx",
      "master",
      "mdb",
      "mcf",
      "mde",
      "mdt",
      "mdf",
      "mdw",
      "mdz",
      "msgx",
      "rem",
      "resources",
      "resx",
      "sdm",
      "sdmDocument",
      "shtm",
      "shtml",
      "sitemap",
      "skin",
      "sln",
      "soap",
      "stm",
      "svc",
      "vbp",
      "vbs",
      "vbproj",
      "vjsproj",
      "vsdisco",
      "vsw",
      "vsmacros",
      "xbap",
      "xaml",
      "xact",
      "webinfo",
    ],
  },
  {
    "category": "java",
    "extensions": [
      "cla",
      "class",
      "ear",
      "jad",
      "jar",
      "war",
    ],
  },
  {
    "category": "turing",
    "extensions": [
      "t",
    ],
  },
  {
    "category": "python",
    "extensions": [
      "py",
      "pyd",
      "py3",
      "pyc",
      "pyo",
      "pyw",
    ],
  },
  {
    "category": "perl",
    "extensions": [
      "pl",
      "pod",
      "pm",
    ],
  },
  {
    "category": "ruby",
    "extensions": [
      "rb",
    ],
  },
  {
    "category": "documents contain macro",
    "extensions": [
      "pptx",
      "xlsx",
      "xlx",
      "docx",
      "docm",
      "dotm",
      "potm",
      "ppam",
      "ppsm",
      "pptm",
      "sldm",
      "xlam",
      "xlsm",
      "xltm",
    ],
  },
  {
    "category": "documents pdf",
    "extensions": [
      "eps",
      "pdf",
      "ps",
      "msg",
    ],
  },
  {
    "category": "legacy documents",
    "extensions": [
      "doc",
      "ppt",
      "xls",
    ],
  },
  {
    "category": "web asset",
    "extensions": [
      "url",
      "its",
      "fxp",
      "fon",
      "fot",
      "chm",
      "appcache",
      "css",
      "eot",
      "htm",
      "html",
      "js",
      "mjs",
      "otf",
      "swf",
      "ttc",
      "ttf",
      "wasm",
      "webapp",
      "webmanifest",
      "woff",
      "woff2",
    ],
  },
]

rule_template = 'MainRule "rx:{extensions_join}" "msg:{msg}" "mz:FILE_EXT" "s:$UPLOAD:8" id:{rule_id};'

extensions = list()
rules = list()
for incr, ident in enumerate(suspicious_list):
  extensions.extend(ident["extensions"])
  rule_id = 1500 + incr
  extensions_join = "|".join(map(lambda ex: "\." + ex.lower(), ident["extensions"]))
  msg = ident["category"] + " extensions"
  print(rule_template.format(
    extensions_join=extensions_join,
    msg=msg,
    rule_id=rule_id,
  ))


# duplicate
extensions.sort()
extensions = list(map(lambda x:x.lower(), extensions))
duplicates = set([x for x in extensions if extensions.count(x) > 1])
if len(duplicates) != 0:
  raise Exception("Duplicate extensions find", duplicates)
